name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Version name"
        required: true

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v2

      - name: Bundle install
        working-directory: ./
        run: bundle install

      - name: Release
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          GITHUB_TOKEN: ${{ secrets.GZ_GITHUB_TOKEN }}
          COCOAPODS_TRUNK_TOKEN: TODO
          GIT_COMMITTER_NAME: Gaetan Zanella
          GIT_AUTHOR_NAME: Gaetan Zanella
          GIT_COMMITTER_EMAIL: gaetan.zanella@fabernovel.com
          GIT_AUTHOR_EMAIL: ci@fabernovel.com
        run: bundle exec fastlane release version:${{ github.event.inputs.name }} bypass_confirmations:true
